name: CI
on: push

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
          cache: 'pip'

      - name: Install dependencies
        run: |
          sudo apt-get update && sudo apt-get install --no-install-recommends -y python3-opengl python3-wxgtk4.0 freeglut3-dev
          pip install pytest

      - name: Run test suite
        run: |
          pytest tests/
