name: CI
on: push

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
          cache: 'pip'

      - name: Install dependencies
        run: |
          apt update && apt install --no-install-recommends -y make gcc libgtk-3-dev freeglut3 freeglut3-dev
          pip install -r requirements.txt

      - name: Run test suite
        run: |
          pytest tests/
